const tableData = [
    {id:1,title:"Chapter 1",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:99,title:"Chapter 2",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:3,title:"Chapter 3",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:4,title:"Chapter 4",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:5,title:"Chapter 5",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:6,title:"Chapter 6",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:7,title:"Chapter 7",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:8,title:"Chapter 8",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:9,title:"Chapter 9",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:10,title:"Chapter 10",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:11,title:"Chapter 11",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:12,title:"Chapter 12",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:13,title:"Chapter 13",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:14,title:"Chapter 14",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:15,title:"Chapter 15",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:16,title:"Chapter 16",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:17,title:"Chapter 17",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:18,title:"Chapter 18",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:19,title:"Chapter 19",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:20,title:"Chapter 20",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:21,title:"Chapter 21",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:22,title:"Chapter 22",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:23,title:"Chapter 23",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:24,title:"Chapter 24",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
{id:25,title:"Chapter 25",tableData:[
    { id: 1, name: "Vocabulary", videoLink: 'https://youtu.be/example1' },
    { id: 2, name: "Grammar", videoLink: 'https://youtu.be/example1' },
    { id: 3, name: "Practice Exercises", videoLink: 'https://youtu.be/example1'},
    { id: 4, name: "Listening", videoLink: 'https://youtu.be/example1' },
    { id: 5, name: "Kanji", videoLink: 'https://youtu.be/example1' },
]},
   
]
  



export default tableData;